namespace Darkages.Enums;

public enum ItemColor
{
    Lavender,
    Black,
    Red,
    Orange,
    Blonde,
    Cyan,
    Blue,
    Mulberry,
    Olive,
    Green,
    Fire,
    Brown,
    Grey,
    Navy,
    Tan,
    White,
    Pink,
    Chartreuse,
    Golden,
    Lemon,
    Royal,
    Platinum,
    Lilac,
    Fuchsia,
    Magenta,
    Peacock,
    NeonPink,
    Arctic,
    Mauve,
    NeonOrange,
    Sky,
    NeonGreen,
    Pistachio,
    Corn,
    Cerulean,
    Chocolate,
    Ruby,
    Hunter,
    Crimson,
    Ocean,
    Ginger,
    Mustard,
    Apple,
    Leaf,
    Cobalt,
    Strawberry,
    Unusual,
    Sea,
    Harlequin,
    Amethyst,
    NeonRed,
    NeonYellow,
    Rose,
    Salmon,
    Scarlet,
    Honey
}

public static class ItemColors
{
    public static int ItemColorsToInt(ItemColor e)
    {
        return e switch
        {
            ItemColor.Lavender => 0,
            ItemColor.Black => 1,
            ItemColor.Red => 2,
            ItemColor.Orange => 3,
            ItemColor.Blonde => 4,
            ItemColor.Cyan => 5,
            ItemColor.Blue => 6,
            ItemColor.Mulberry => 7,
            ItemColor.Olive => 8,
            ItemColor.Green => 9,
            ItemColor.Fire => 10,
            ItemColor.Brown => 11,
            ItemColor.Grey => 12,
            ItemColor.Navy => 13,
            ItemColor.Tan => 14,
            ItemColor.White => 15,
            ItemColor.Pink => 16,
            ItemColor.Chartreuse => 17,
            ItemColor.Golden => 18,
            ItemColor.Lemon => 19,
            ItemColor.Royal => 20,
            ItemColor.Platinum => 21,
            ItemColor.Lilac => 22,
            ItemColor.Fuchsia => 23,
            ItemColor.Magenta => 24,
            ItemColor.Peacock => 25,
            ItemColor.NeonPink => 26,
            ItemColor.Arctic => 27,
            ItemColor.Mauve => 28,
            ItemColor.NeonOrange => 29,
            ItemColor.Sky => 30,
            ItemColor.NeonGreen => 31,
            ItemColor.Pistachio => 32,
            ItemColor.Corn => 33,
            ItemColor.Cerulean => 34,
            ItemColor.Chocolate => 35,
            ItemColor.Ruby => 36,
            ItemColor.Hunter => 37,
            ItemColor.Crimson => 38,
            ItemColor.Ocean => 39,
            ItemColor.Ginger => 40,
            ItemColor.Mustard => 41,
            ItemColor.Apple => 42,
            ItemColor.Leaf => 43,
            ItemColor.Cobalt => 44,
            ItemColor.Strawberry => 45,
            ItemColor.Unusual => 46,
            ItemColor.Sea => 47,
            ItemColor.Harlequin => 48,
            ItemColor.Amethyst => 49,
            ItemColor.NeonRed => 50,
            ItemColor.NeonYellow => 51,
            ItemColor.Rose => 52,
            ItemColor.Salmon => 53,
            ItemColor.Scarlet => 54,
            ItemColor.Honey => 55,
            _ => 0
        };
    }
}